#!/usr/bin/env python3
"""Validate the ordered test-scene cover used for paper full-scene inference.

The cover CSV is an ordered list of block IDs. Anchors must occupy the first 264
rows and supplemental blocks the final 148 rows. Flat tile exports generated by
blockgroup_infer.py follow this order, with the last covering block retaining
ownership when a tile occurs more than once.
"""
import argparse
import csv
from pathlib import Path


QUADRANT_COLUMNS = (
    "top_left_patch_id",
    "top_right_patch_id",
    "bottom_left_patch_id",
    "bottom_right_patch_id",
)
EXCLUDED_LABELS = {"0", "1", "5"}


def read_csv(path):
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def as_bool(value):
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def require(condition, message, errors):
    if not condition:
        errors.append(message)


def main():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cover", type=Path,
                        default=root / "manifests" / "scene_cover_test.csv")
    parser.add_argument("--block-index", type=Path,
                        default=root / "manifests" / "block_2x2_index.csv")
    parser.add_argument("--patch-index", type=Path,
                        default=root / "manifests" / "patch_index.csv")
    args = parser.parse_args()

    for path in (args.cover, args.block_index, args.patch_index):
        if not path.is_file():
            raise SystemExit(f"missing required file: {path}")

    blocks = read_csv(args.block_index)
    patches = read_csv(args.patch_index)
    cover_rows = read_csv(args.cover)
    block_by_id = {row.get("block_id", "").strip(): row for row in blocks}
    errors = []

    require(bool(cover_rows), "cover CSV is empty", errors)
    require(all("block_id" in row for row in cover_rows),
            "cover CSV must contain a block_id column", errors)
    cover_ids = [row.get("block_id", "").strip() for row in cover_rows]
    require(all(cover_ids), "cover CSV contains an empty block_id", errors)
    require(len(cover_ids) == 412, f"expected 412 cover rows, found {len(cover_ids)}", errors)
    require(len(set(cover_ids)) == len(cover_ids), "cover contains duplicate block IDs", errors)

    missing_ids = [block_id for block_id in cover_ids if block_id not in block_by_id]
    require(not missing_ids,
            f"cover contains {len(missing_ids)} block IDs absent from block index: {missing_ids[:5]}",
            errors)
    resolved = [block_by_id[block_id] for block_id in cover_ids if block_id in block_by_id]

    if len(resolved) == len(cover_ids):
        anchors = [as_bool(row.get("use_for_tiling_eval")) for row in resolved]
        require(sum(anchors) == 264,
                f"expected 264 anchor blocks, found {sum(anchors)}", errors)
        require(all(anchors[:264]), "the first 264 cover rows must all be anchors", errors)
        require(not any(anchors[264:]), "supplemental rows must follow all anchors", errors)
        require(all(as_bool(row.get("all_four_valid")) for row in resolved),
                "every cover block must have all_four_valid=true", errors)
        require(all(row.get("split", "").strip().lower() == "test" for row in resolved),
                "every cover block must belong to the test split", errors)

        tile_memberships = [row[column].strip() for row in resolved for column in QUADRANT_COLUMNS]
        unique_tiles = set(tile_memberships)
        cover_cities = {row.get("city", "").strip() for row in resolved}
        require(len(unique_tiles) == 1231,
                f"expected 1,231 unique covered tiles, found {len(unique_tiles)}", errors)
        require(len(cover_cities) == 18,
                f"expected 18 effective cover cities, found {len(cover_cities)}", errors)

        usable_test = {
            row.get("patch_id", "").strip()
            for row in patches
            if row.get("split", "").strip().lower() == "test"
            and row.get("coarse_label", "").strip() not in EXCLUDED_LABELS
        }
        assigned_test_cities = {
            row.get("city", "").strip()
            for row in patches
            if row.get("split", "").strip().lower() == "test"
        }
        require(len(usable_test) == 1234,
                f"expected 1,234 usable test tiles, found {len(usable_test)}", errors)
        require(len(assigned_test_cities) == 19,
                f"expected 19 assigned test cities, found {len(assigned_test_cities)}", errors)
        require(unique_tiles <= usable_test, "cover contains tiles outside the usable test set", errors)
        uncovered = usable_test - unique_tiles
        require(len(uncovered) == 3,
                f"expected 3 uncovered usable test tiles, found {len(uncovered)}", errors)

        valid_block_tiles = {
            row[column].strip()
            for row in blocks
            if row.get("split", "").strip().lower() == "test"
            and as_bool(row.get("all_four_valid"))
            for column in QUADRANT_COLUMNS
        }
        require(not (uncovered & valid_block_tiles),
                "an uncovered usable tile appears in an all-valid test block", errors)

        duplicate_memberships = len(tile_memberships) - len(unique_tiles)
        print(f"cover rows:             {len(cover_ids)} (264 anchors + 148 supplemental)")
        print(f"unique covered tiles:   {len(unique_tiles)} / {len(usable_test)}")
        print(f"duplicate memberships:  {duplicate_memberships} (last covering block wins)")
        print(f"effective cover cities: {len(cover_cities)} / {len(assigned_test_cities)} assigned test cities")
        print(f"uncovered usable tiles: {', '.join(sorted(uncovered))}")

    if errors:
        for message in errors:
            print(f"[FAIL] {message}")
        raise SystemExit(f"scene-cover validation failed with {len(errors)} error(s)")
    print("[OK] ordered scene cover matches all frozen paper invariants")


if __name__ == "__main__":
    main()
